'use client';
import { useEffect, useState } from 'react';

export default function AdminPage() {
  const [authed,setAuthed]=useState(false), [configured,setConfigured]=useState(false);
  const [apiId,setApiId]=useState(''), [apiHash,setApiHash]=useState(''), [pin,setPin]=useState(''), [msg,setMsg]=useState('');
  async function refresh(){const r=await fetch('/api/admin/config',{cache:'no-store'});setAuthed(r.status!==401);if(r.ok){const j=await r.json();setConfigured(j.configured);setApiId(j.apiId?String(j.apiId):'')}}
  useEffect(()=>{refresh().catch(()=>{})},[]);
  async function login(e:React.FormEvent){e.preventDefault();setMsg('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});if(r.ok){setAuthed(true);await refresh()}else setMsg('Wrong PIN')}
  async function save(e:React.FormEvent){e.preventDefault();setMsg('Saving…');const r=await fetch('/api/admin/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({apiId:Number(apiId),apiHash})});const j=await r.json().catch(()=>({}));if(r.ok){setConfigured(true);setApiHash('');setMsg('Saved globally. New HEPlay clients can sign in with QR.')}else setMsg(j.error||'Save failed')}
  if(!authed)return <main className="wrap"><div className="brand"><span>HE</span>PLAY</div><div className="card" style={{maxWidth:480}}><div className="eyebrow">CLOUD ADMIN</div><h1>Unlock HEPlay</h1><p className="muted">Only the owner configures the Telegram application credentials.</p><form onSubmit={login}><label>Admin PIN</label><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="••••••"/><button>Continue</button></form>{msg&&<div className="msg bad">{msg}</div>}</div></main>;
  return <main className="wrap"><div className="row"><div className="brand"><span>HE</span>PLAY</div><span className="pill">{configured?'Configured':'Not configured'}</span></div><div className="grid"><section className="card"><div className="eyebrow">GLOBAL TELEGRAM APP</div><h1>Multi-user configuration</h1><p className="muted">Set this once. Every HEPlay installation fetches it automatically; every user still logs into their own Telegram account with QR.</p><form onSubmit={save}><label>Telegram API ID</label><input inputMode="numeric" value={apiId} onChange={e=>setApiId(e.target.value)} placeholder="12345678" required/><label>Telegram API hash</label><input type="password" value={apiHash} onChange={e=>setApiHash(e.target.value)} placeholder={configured?'Enter a hash only when replacing it':'Paste API hash'} required/><button>Save globally</button></form>{msg&&<div className="msg">{msg}</div>}</section><aside className="card"><div className="eyebrow">ISOLATION</div><h2>One app. Many Telegram accounts.</h2><p className="muted">Only the Telegram application ID/hash are shared. Authorization, channels, Saved Messages, playback and TDLib data stay on each Fire TV.</p><p><b>Owner panel</b><br/><span className="muted">/admin</span></p><p><b>TV config API</b><br/><span className="muted">/api/config</span></p></aside></div></main>;
}
