"use client";

import {useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,Eye,EyeOff,KeyRound,LogOut,MessageSquareText,Search,ShieldAlert,ShieldCheck,Target,UserCheck,UserX,Users,X} from "lucide-react";

type Student={id:string;name:string;username:string;email:string;passwordHash:string;securityHash:string;course:string|null;university:string|null;year:number|null;semester:number|null;xp:number;level:number;streak:number;banned:boolean;lastActiveAt:string|null;createdAt:string;updatedAt:string;completed:number;progressAverage:number;bestScore:number;attempts:number;mockAttempts:number;messages:number;feedbackCount:number;aiMessages:number};
type FeedbackItem={id:string;user:string;message:string;status:string;adminReply:string|null;createdAt:string};
type Data={totalStudents:number;activeStudents:number;bannedStudents:number;totalTopics:number;averageProgress:number;students:Student[];feedback:FeedbackItem[]};

export function AdminClient({mode,data}:{mode:"login"|"dashboard";data?:Data}){
 const [username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[error,setError]=useState("");
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[selected,setSelected]=useState<Student|null>(null);
 const [feedback,setFeedback]=useState(data?.feedback??[]),[replying,setReplying]=useState<Record<string,string>>({});
 const [currentPw,setCurrentPw]=useState(""),[newPw,setNewPw]=useState(""),[notice,setNotice]=useState(""),[showHashes,setShowHashes]=useState(false),[hydrated,setHydrated]=useState(false);
 useEffect(()=>setHydrated(true),[]);

 async function login(e:React.FormEvent){e.preventDefault();setError("");try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"Invalid credentials.");return;}location.href="/admin"}catch{setError("Could not reach the server.")}}
 async function ban(s:Student){const action=s.banned?"UNBAN":"BAN";if(!confirm(`${action==="BAN"?"Ban":"Unban"} @${s.username}?`))return;const r=await fetch("/api/admin/users/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:s.id,action})});const j=await r.json();if(!r.ok){alert(j.error||"Could not update.");return;}s.banned=j.user.banned;setSelected({...s});}
 async function reply(id:string){const text=(replying[id]||"").trim();if(!text)return;const r=await fetch("/api/admin/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,reply:text})});if(r.ok){setFeedback(v=>v.map(f=>f.id===id?{...f,status:"REPLIED",adminReply:text}:f));setReplying(v=>({...v,[id]:""}));}}
 async function changePassword(){setNotice("");const r=await fetch("/api/admin/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:currentPw,newPassword:newPw})});const j=await r.json().catch(()=>({}));setNotice(j.message||j.error||"Done");if(r.ok){setCurrentPw("");setNewPw("");setTimeout(()=>location.href="/admin",700)}}
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return (data?.students??[]).filter(s=>(filter==="ALL"||(filter==="ACTIVE"&&!s.banned)||(filter==="BANNED"&&s.banned))&&(!q||[s.name,s.username,s.email,s.course||"",s.university||""].some(v=>v.toLowerCase().includes(q))))},[data?.students,query,filter]);
 const when=(iso:string|null)=>{if(!iso)return"Never";if(!hydrated)return"—";const d=Math.max(0,Date.now()-new Date(iso).getTime());if(d<5*60*1000)return"Online";const h=Math.floor(d/3600000);return h<24?`${Math.max(1,h)}h ago`:`${Math.floor(h/24)}d ago`};
 if(mode==="login") return <main className="admin-auth"><form className="admin-login-card" onSubmit={login}><div className="admin-shield"><ShieldCheck size={25}/></div><div className="eyebrow">PRIVATE ADMIN AREA</div><h1>Control room.</h1><p className="muted">Students, moderation, feedback and settings.</p><label>Username<input suppressHydrationWarning className="input" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>Password<input suppressHydrationWarning className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p className="error-text">{error}</p>}<button className="btn admin-submit">Sign in →</button><p className="admin-security-note">Server-side session · bcrypt · throttled login</p></form></main>;

 return <main className="admin-page">
  <header className="admin-header"><div><div className="eyebrow">CONTROL ROOM</div><h1 className="h1">Admin dashboard.</h1><p className="muted">See users, progress, moderation and student feedback.</p></div><form action="/api/admin/logout" method="post"><button className="btn secondary"><LogOut size={15}/> Log out</button></form></header>
  <section className="admin-stats">
   <div className="card admin-stat"><Users size={18}/><div className="eyebrow">STUDENTS</div><b>{data?.totalStudents??0}</b><span>{data?.activeStudents??0} online · {data?.bannedStudents??0} banned</span></div>
   <div className="card admin-stat"><BarChart3 size={18}/><div className="eyebrow">AVG. PROGRESS</div><b>{data?.averageProgress??0}%</b><span>Across all students</span></div>
   <div className="card admin-stat"><Target size={18}/><div className="eyebrow">CURRICULUM</div><b>{data?.totalTopics??0}</b><span>Total study topics</span></div>
   <div className="card admin-stat"><MessageSquareText size={18}/><div className="eyebrow">FEEDBACK</div><b>{feedback.length}</b><span>Reports in inbox</span></div>
  </section>

  <section className="card admin-section"><div className="admin-section-head"><div><div className="eyebrow">STUDENT DIRECTORY</div><h2 className="h2">Every account.</h2><p className="muted">Search and click a student for full details.</p></div><span className="pill">{visible.length} shown</span></div>
   <div className="admin-directory-controls"><div className="admin-search"><Search size={15}/><input suppressHydrationWarning value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, username, email…"/></div><div className="admin-filters">{["ALL","ACTIVE","BANNED"].map(v=><button type="button" key={v} className={`filter-btn ${filter===v?"selected":""}`} onClick={()=>setFilter(v)}>{v}</button>)}</div></div>
   <div className="admin-table admin-users-table"><div className="admin-table-row admin-table-head"><span>#</span><span>Student</span><span>Email</span><span>Course</span><span>Progress</span><span>Last active</span><span>Access</span></div>
    {visible.map((s,i)=><button type="button" className="admin-table-row admin-user-row" key={s.id} onClick={()=>setSelected(s)}><span>{i+1}</span><span><strong>@{s.username}</strong><small>{s.name}</small></span><span className="truncate">{s.email}</span><span>{s.course||"Not set"}{s.year?` · Y${s.year}`:""}</span><span>{s.progressAverage}% · {s.completed} done</span><span><i className={`tiny-dot ${when(s.lastActiveAt)==="Online"?"on":""}`}/>{when(s.lastActiveAt)}</span><span className={`status ${s.banned?"status-banned":"status-live"}`}>{s.banned?"BANNED":"ACTIVE"}</span></button>)}
   </div>
   {!visible.length&&<div className="admin-empty"><Users size={18}/><strong>No matching students.</strong><span>Try a different search/filter.</span></div>}
  </section>

  <section className="card admin-section"><div className="admin-section-head"><div><div className="eyebrow">FEEDBACK INBOX</div><h2 className="h2">Student reports.</h2></div></div><div className="admin-feedback-list">{feedback.length===0?<div className="admin-empty"><CheckCircle2 size={18}/><strong>Nothing waiting.</strong></div>:feedback.map(f=><article className="admin-feedback" key={f.id}><div className="between"><div><strong>@{f.user}</strong><small className="feedback-date">{f.createdAt.slice(0,10)}</small></div><span className="status">{f.status}</span></div><p>{f.message}</p>{f.adminReply&&<div className="admin-reply"><div className="eyebrow">REPLY</div><p>{f.adminReply}</p></div>}<div className="admin-reply-form"><input suppressHydrationWarning className="input" value={replying[f.id]||""} onChange={e=>setReplying(v=>({...v,[f.id]:e.target.value}))} placeholder="Write a reply…"/><button className="btn" type="button" onClick={()=>void reply(f.id)}>Reply →</button></div></article>)}</div></section>

  <section className="card admin-section"><div className="admin-section-head"><div><div className="eyebrow">ADMIN SECURITY</div><h2 className="h2">Change admin password.</h2><p className="muted">Changing it signs you out of the current session.</p></div><KeyRound size={20}/></div><div className="admin-password-grid"><input suppressHydrationWarning className="input" type="password" value={currentPw} onChange={e=>setCurrentPw(e.target.value)} placeholder="Current password"/><input suppressHydrationWarning className="input" type="password" value={newPw} onChange={e=>setNewPw(e.target.value)} placeholder="New password · 10+ chars"/><button className="btn" type="button" disabled={newPw.length<10||!currentPw} onClick={()=>void changePassword()}>Change password →</button></div>{notice&&<p className="muted">{notice}</p>}</section>

  {selected&&<div className="admin-modal-backdrop" onClick={()=>setSelected(null)}><section className="admin-user-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={()=>setSelected(null)}><X size={18}/></button><div className="admin-modal-top"><div className="avatar">{selected.username[0].toUpperCase()}</div><div><div className="eyebrow">FULL STUDENT PROFILE</div><h2>@{selected.username}</h2><p className="muted">{selected.name}</p></div></div><div className="admin-profile-grid">{[["Email",selected.email],["Course",selected.course||"Not set"],["University",selected.university||"Not set"],["Year / semester",`${selected.year??"—"} / ${selected.semester??"—"}`],["XP / level",`${selected.xp} / ${selected.level}`],["Streak",`${selected.streak} days`],["Progress",`${selected.progressAverage}%`],["Best score",`${selected.bestScore}%`],["MCQ attempts",String(selected.attempts)],["Mock attempts",String(selected.mockAttempts)],["Community messages",String(selected.messages)],["AI messages",String(selected.aiMessages)],["Feedback",String(selected.feedbackCount)],["Joined",selected.createdAt.slice(0,10)],["Last active",when(selected.lastActiveAt)],["Account ID",selected.id]].map(([k,v])=><div className="admin-profile-cell" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="admin-hash-section"><button type="button" className="text-btn" onClick={()=>setShowHashes(v=>!v)}>{showHashes?<EyeOff size={14}/>:<Eye size={14}/>} {showHashes?"Hide":"Show"} credential hashes</button>{showHashes&&<div className="hash-box"><div><b>Password hash</b><code>{selected.passwordHash}</code></div><div><b>Security hash</b><code>{selected.securityHash}</code></div></div>}<p className="admin-sensitive-note">Hashes are sensitive. Never share them publicly.</p></div><div className="admin-modal-actions"><button type="button" className="btn danger-btn" onClick={()=>void ban(selected)}>{selected.banned?<><UserCheck size={15}/> Unban student</>:<><UserX size={15}/> Ban student</>}</button></div></section></div>}
 </main>
}
